// THE CATALOG — everything typically found in a short-term rental (Jon, 2026-09-03: "you're creating
// default items when you shouldn't. There should be a search or dropdown to add items. Full list for
// what's typically found at a property.")
//
// A room starts EMPTY. The walker searches this list and taps what is actually there; the count and
// condition come with the tap. The inventory standard (lib/onboarding.ts) still says what a unit of
// this shape SHOULD hold — that is the "expected here" checklist and the buy list — but nothing is
// written into a room until a person adds it.
//
// Isomorphic (no server imports). `kinds` = the rooms this item is typical for; search ranks those
// first for the room you are standing in. Aliases catch the words people actually type.
import type { Category, RoomKind } from './onboarding'

export type CatalogItem = { name: string; category: Category; kinds: RoomKind[]; aliases?: string[]; countable?: boolean; brand?: 'size' | 'model' }
type K = RoomKind
const C = (name: string, category: Category, kinds: K[], extra: Partial<CatalogItem> = {}): CatalogItem => ({ name, category, kinds, ...extra })
const ALL: K[] = ['entry', 'living', 'kitchen', 'dining', 'bedroom', 'bathroom', 'balcony', 'laundry', 'office', 'other']

export const CATALOG: CatalogItem[] = [
  // ── SAFETY & ACCESS ────────────────────────────────────────────────────────────────────────────
  C('Smart lock / keypad', 'safety', ['entry'], { aliases: ['door lock', 'schlage', 'yale', 'august'] }),
  C('Smoke detector', 'safety', ['entry', 'bedroom', 'living', 'kitchen'], { aliases: ['smoke alarm'] }),
  C('Carbon monoxide detector', 'safety', ['entry', 'bedroom', 'living'], { aliases: ['CO detector', 'co alarm'] }),
  C('Fire extinguisher', 'safety', ['kitchen', 'entry']),
  C('First-aid kit', 'safety', ['entry', 'bathroom', 'kitchen']),
  C('Flashlight', 'safety', ['entry', 'bedroom']),
  C('Safe', 'safety', ['bedroom', 'entry'], { aliases: ['lockbox'] }),
  C('Fire blanket', 'safety', ['kitchen']),
  C('Emergency exit map', 'safety', ['entry']),
  C('Key lockbox', 'safety', ['entry']),
  C('Doorbell / camera', 'electronics', ['entry'], { aliases: ['ring', 'video doorbell'] }),
  C('Noise monitor', 'electronics', ['entry', 'living'], { aliases: ['minut', 'noiseaware'] }),
  C('Wi-Fi router', 'electronics', ['entry', 'office', 'living'], { aliases: ['modem', 'internet'] }),
  C('A/C thermostat', 'appliance', ['entry', 'living', 'bedroom'], { aliases: ['nest', 'ecobee', 'thermostat'] }),
  C('Portable A/C unit', 'appliance', ['bedroom', 'living'], { brand: 'model' }),
  C('Space heater', 'appliance', ['bedroom', 'living'], { brand: 'model' }),
  C('Dehumidifier', 'appliance', ['laundry', 'living', 'bedroom'], { brand: 'model' }),
  C('Air purifier', 'appliance', ['bedroom', 'living'], { brand: 'model' }),
  C('Ceiling fan', 'appliance', ['bedroom', 'living', 'balcony']),
  C('Fan', 'appliance', ['bedroom', 'living'], { aliases: ['standing fan', 'tower fan'] }),

  // ── ENTRY ──────────────────────────────────────────────────────────────────────────────────────
  C('Doormat', 'decor', ['entry', 'balcony']),
  C('Console table', 'furniture', ['entry', 'living']),
  C('Coat hooks / rack', 'furniture', ['entry'], { aliases: ['hooks', 'coat rack'] }),
  C('Shoe rack / tray', 'furniture', ['entry']),
  C('Umbrella', 'other', ['entry']),
  C('Umbrella stand', 'decor', ['entry']),
  C('Luggage rack', 'furniture', ['bedroom', 'entry']),
  C('Bench', 'furniture', ['entry', 'bedroom', 'dining']),
  C('Key bowl / tray', 'decor', ['entry']),
  C('Welcome book / house manual', 'other', ['entry', 'living'], { aliases: ['guidebook', 'binder'] }),

  // ── LIVING ─────────────────────────────────────────────────────────────────────────────────────
  C('Sofa', 'furniture', ['living'], { aliases: ['couch'] }),
  C('Sectional sofa', 'furniture', ['living'], { aliases: ['sectional', 'couch'] }),
  C('Sleeper sofa', 'furniture', ['living', 'office'], { aliases: ['pull-out', 'sofa bed', 'couch'] }),
  C('Sleeper sofa bedding set', 'linen', ['living'], { aliases: ['sofa bed sheets'] }),
  C('Sleeper sofa pillows', 'linen', ['living'], { countable: true }),
  C('Loveseat', 'furniture', ['living']),
  C('Armchair', 'furniture', ['living', 'bedroom'], { aliases: ['accent chair'] }),
  C('Recliner', 'furniture', ['living']),
  C('Ottoman / pouf', 'furniture', ['living', 'bedroom']),
  C('Coffee table', 'furniture', ['living']),
  C('Side table', 'furniture', ['living', 'bedroom', 'balcony'], { aliases: ['end table'] }),
  C('Console / TV stand', 'furniture', ['living', 'bedroom'], { aliases: ['media console', 'tv stand'] }),
  C('Bookshelf', 'furniture', ['living', 'office', 'bedroom']),
  C('Bar cart', 'furniture', ['living', 'dining']),
  C('TV', 'electronics', ['living', 'bedroom', 'office'], { brand: 'size', aliases: ['television', 'smart tv'] }),
  C('TV remote', 'electronics', ['living', 'bedroom']),
  C('TV wall mount', 'electronics', ['living', 'bedroom']),
  C('Streaming device', 'electronics', ['living', 'bedroom'], { aliases: ['roku', 'apple tv', 'fire stick', 'chromecast'] }),
  C('Soundbar', 'electronics', ['living']),
  C('Bluetooth speaker', 'electronics', ['living', 'kitchen', 'balcony'], { aliases: ['sonos', 'speaker'] }),
  C('Smart speaker', 'electronics', ['living', 'kitchen'], { aliases: ['alexa', 'echo', 'google home'] }),
  C('Universal remote', 'electronics', ['living']),
  C('Floor lamp', 'decor', ['living', 'bedroom', 'office']),
  C('Table lamp', 'decor', ['living', 'bedroom', 'office', 'entry']),
  C('Rug', 'decor', ['living', 'bedroom', 'dining', 'entry', 'office'], { aliases: ['area rug', 'carpet'] }),
  C('Curtains / drapes', 'decor', ['living', 'bedroom', 'dining'], { aliases: ['drapes'] }),
  C('Blinds / shades', 'decor', ['living', 'bedroom', 'kitchen', 'bathroom'], { aliases: ['shades', 'roller'] }),
  C('Blackout curtains', 'decor', ['bedroom']),
  C('Throw pillows', 'decor', ['living', 'bedroom'], { countable: true, aliases: ['cushions', 'pillows'] }),
  C('Throw blanket', 'linen', ['living', 'bedroom'], { countable: true, aliases: ['throw'] }),
  C('Wall art', 'decor', ALL, { countable: true, aliases: ['picture', 'painting', 'print', 'frame'] }),
  C('Mirror', 'decor', ['entry', 'bedroom', 'bathroom', 'living']),
  C('Plants / greenery', 'decor', ['living', 'bedroom', 'balcony', 'entry'], { countable: true, aliases: ['plant', 'faux plant'] }),
  C('Vase', 'decor', ['living', 'dining', 'entry']),
  C('Decorative tray', 'decor', ['living', 'kitchen']),
  C('Candles / holders', 'decor', ['living', 'dining']),
  C('Clock', 'decor', ['living', 'kitchen', 'bedroom']),
  C('Board games', 'other', ['living'], { countable: true, aliases: ['games'] }),
  C('Books / magazines', 'other', ['living', 'bedroom'], { countable: true }),
  C('Playing cards', 'other', ['living']),
  C('Puzzle', 'other', ['living']),
  C('Charging station / USB', 'electronics', ['living', 'bedroom', 'entry'], { aliases: ['charger', 'usb'] }),
  C('Power strip', 'electronics', ['living', 'bedroom', 'office']),
  C('Coasters', 'kitchen', ['living', 'dining'], { countable: true }),
  C('Fireplace tools', 'other', ['living']),
  C('Yoga mat', 'other', ['living', 'bedroom']),

  // ── KITCHEN — APPLIANCES ───────────────────────────────────────────────────────────────────────
  C('Refrigerator', 'appliance', ['kitchen'], { brand: 'model', aliases: ['fridge', 'freezer'] }),
  C('Mini fridge', 'appliance', ['kitchen', 'bedroom', 'living'], { brand: 'model' }),
  C('Stove / oven (range)', 'appliance', ['kitchen'], { brand: 'model', aliases: ['stove', 'oven', 'range'] }),
  C('Cooktop', 'appliance', ['kitchen'], { brand: 'model', aliases: ['hob', 'induction'] }),
  C('Wall oven', 'appliance', ['kitchen'], { brand: 'model' }),
  C('Range hood', 'appliance', ['kitchen'], { aliases: ['vent hood', 'exhaust'] }),
  C('Microwave', 'appliance', ['kitchen'], { brand: 'model' }),
  C('Dishwasher', 'appliance', ['kitchen'], { brand: 'model' }),
  C('Garbage disposal', 'appliance', ['kitchen'], { aliases: ['disposal'] }),
  C('Coffee maker (drip)', 'appliance', ['kitchen'], { brand: 'model', aliases: ['coffee', 'mr coffee', 'drip'] }),
  C('Keurig / pod coffee maker', 'appliance', ['kitchen'], { brand: 'model', aliases: ['keurig', 'pods', 'k-cup'] }),
  C('Espresso / Nespresso machine', 'appliance', ['kitchen'], { brand: 'model', aliases: ['nespresso', 'espresso'] }),
  C('French press', 'kitchen', ['kitchen']),
  C('Coffee grinder', 'appliance', ['kitchen']),
  C('Kettle', 'appliance', ['kitchen'], { aliases: ['electric kettle', 'tea kettle'] }),
  C('Toaster', 'appliance', ['kitchen']),
  C('Toaster oven', 'appliance', ['kitchen'], { brand: 'model' }),
  C('Blender', 'appliance', ['kitchen'], { brand: 'model', aliases: ['ninja', 'vitamix'] }),
  C('Hand mixer', 'appliance', ['kitchen']),
  C('Stand mixer', 'appliance', ['kitchen'], { brand: 'model', aliases: ['kitchenaid'] }),
  C('Food processor', 'appliance', ['kitchen']),
  C('Air fryer', 'appliance', ['kitchen'], { brand: 'model' }),
  C('Slow cooker / Instant Pot', 'appliance', ['kitchen'], { brand: 'model', aliases: ['crockpot', 'instant pot', 'pressure cooker'] }),
  C('Rice cooker', 'appliance', ['kitchen']),
  C('Waffle maker', 'appliance', ['kitchen']),
  C('Griddle / panini press', 'appliance', ['kitchen']),
  C('Wine fridge', 'appliance', ['kitchen', 'dining'], { brand: 'model' }),
  C('Ice maker', 'appliance', ['kitchen'], { brand: 'model' }),
  C('Water filter / pitcher', 'kitchen', ['kitchen'], { aliases: ['brita'] }),
  C('Electric can opener', 'appliance', ['kitchen']),

  // ── KITCHEN — COOKWARE & BAKEWARE ──────────────────────────────────────────────────────────────
  C('Frying pan 8in', 'kitchen', ['kitchen'], { aliases: ['skillet', 'small pan'] }),
  C('Frying pan 10in', 'kitchen', ['kitchen'], { aliases: ['skillet', 'non-stick pan'] }),
  C('Frying pan 12in', 'kitchen', ['kitchen'], { aliases: ['skillet', 'large pan'] }),
  C('Cast iron skillet', 'kitchen', ['kitchen']),
  C('Saucepan 1.5qt w/ lid', 'kitchen', ['kitchen'], { aliases: ['small pot'] }),
  C('Saucepan 3qt w/ lid', 'kitchen', ['kitchen'], { aliases: ['pot'] }),
  C('Sauté pan w/ lid', 'kitchen', ['kitchen']),
  C('Stock pot 8qt w/ lid', 'kitchen', ['kitchen'], { aliases: ['large pot', 'pasta pot'] }),
  C('Dutch oven', 'kitchen', ['kitchen']),
  C('Wok', 'kitchen', ['kitchen']),
  C('Grill pan', 'kitchen', ['kitchen']),
  C('Baking sheet', 'kitchen', ['kitchen'], { countable: true, aliases: ['cookie sheet', 'sheet pan'] }),
  C('Baking dish 9x13', 'kitchen', ['kitchen'], { aliases: ['casserole dish', 'pyrex'] }),
  C('Baking dish 8x8', 'kitchen', ['kitchen']),
  C('Roasting pan', 'kitchen', ['kitchen']),
  C('Muffin pan', 'kitchen', ['kitchen']),
  C('Loaf pan', 'kitchen', ['kitchen']),
  C('Cake pan', 'kitchen', ['kitchen']),
  C('Pizza pan / stone', 'kitchen', ['kitchen']),
  C('Mixing bowls', 'kitchen', ['kitchen'], { countable: true }),
  C('Colander / strainer', 'kitchen', ['kitchen']),
  C('Cooling rack', 'kitchen', ['kitchen']),

  // ── KITCHEN — KNIVES & TOOLS ───────────────────────────────────────────────────────────────────
  C("Chef's knife", 'kitchen', ['kitchen'], { aliases: ['knife'] }),
  C('Paring knife', 'kitchen', ['kitchen']),
  C('Bread knife', 'kitchen', ['kitchen'], { aliases: ['serrated knife'] }),
  C('Steak knives', 'kitchen', ['kitchen', 'dining'], { countable: true }),
  C('Knife block / magnet', 'kitchen', ['kitchen']),
  C('Knife sharpener', 'kitchen', ['kitchen']),
  C('Kitchen shears', 'kitchen', ['kitchen'], { aliases: ['scissors'] }),
  C('Cutting board', 'kitchen', ['kitchen'], { countable: true, aliases: ['chopping board'] }),
  C('Spatula', 'kitchen', ['kitchen'], { countable: true, aliases: ['turner', 'flipper'] }),
  C('Silicone spatula', 'kitchen', ['kitchen'], { countable: true }),
  C('Wooden spoon', 'kitchen', ['kitchen'], { countable: true }),
  C('Slotted spoon', 'kitchen', ['kitchen']),
  C('Serving spoon (big spoon)', 'kitchen', ['kitchen', 'dining'], { countable: true, aliases: ['big spoon', 'serving spoons'] }),
  C('Serving fork', 'kitchen', ['kitchen', 'dining'], { countable: true }),
  C('Ladle', 'kitchen', ['kitchen']),
  C('Tongs', 'kitchen', ['kitchen'], { countable: true }),
  C('Whisk', 'kitchen', ['kitchen']),
  C('Can opener', 'kitchen', ['kitchen']),
  C('Wine / bottle opener', 'kitchen', ['kitchen', 'dining'], { aliases: ['corkscrew', 'bottle opener'] }),
  C('Measuring cups set', 'kitchen', ['kitchen']),
  C('Measuring spoons set', 'kitchen', ['kitchen']),
  C('Peeler', 'kitchen', ['kitchen']),
  C('Grater', 'kitchen', ['kitchen'], { aliases: ['zester', 'box grater'] }),
  C('Garlic press', 'kitchen', ['kitchen']),
  C('Potato masher', 'kitchen', ['kitchen']),
  C('Pizza cutter', 'kitchen', ['kitchen']),
  C('Rolling pin', 'kitchen', ['kitchen']),
  C('Cooking thermometer', 'kitchen', ['kitchen']),
  C('Ice cream scoop', 'kitchen', ['kitchen']),
  C('Oven mitts', 'kitchen', ['kitchen'], { countable: true, aliases: ['pot holders'] }),
  C('Trivets', 'kitchen', ['kitchen', 'dining'], { countable: true }),
  C('Salad spinner', 'kitchen', ['kitchen']),
  C('Cocktail shaker set', 'kitchen', ['kitchen'], { aliases: ['bar set'] }),
  C('Ice bucket / tongs', 'kitchen', ['kitchen', 'dining']),
  C('Pitcher', 'kitchen', ['kitchen', 'dining']),

  // ── KITCHEN — TABLEWARE & DRINKWARE ────────────────────────────────────────────────────────────
  C('Dinner plates', 'kitchen', ['kitchen', 'dining'], { countable: true, aliases: ['plates'] }),
  C('Salad / side plates', 'kitchen', ['kitchen', 'dining'], { countable: true, aliases: ['small plates', 'dessert plates'] }),
  C('Bowls', 'kitchen', ['kitchen', 'dining'], { countable: true, aliases: ['cereal bowls', 'soup bowls'] }),
  C('Pasta bowls', 'kitchen', ['kitchen', 'dining'], { countable: true }),
  C('Mugs', 'kitchen', ['kitchen'], { countable: true, aliases: ['coffee cups', 'cups'] }),
  C('Espresso cups', 'kitchen', ['kitchen'], { countable: true }),
  C('Water glasses', 'kitchen', ['kitchen', 'dining'], { countable: true, aliases: ['glasses', 'tumblers', 'cups'] }),
  C('Highball glasses', 'kitchen', ['kitchen'], { countable: true }),
  C('Wine glasses', 'kitchen', ['kitchen', 'dining'], { countable: true, aliases: ['stemless'] }),
  C('Champagne flutes', 'kitchen', ['kitchen', 'dining'], { countable: true }),
  C('Rocks / whiskey glasses', 'kitchen', ['kitchen'], { countable: true }),
  C('Beer glasses', 'kitchen', ['kitchen'], { countable: true }),
  C('Kids plastic cups / plates', 'kitchen', ['kitchen'], { countable: true, aliases: ['plastic cups', 'kids'] }),
  C('Forks', 'kitchen', ['kitchen', 'dining'], { countable: true, aliases: ['silverware', 'cutlery', 'flatware'] }),
  C('Knives (table)', 'kitchen', ['kitchen', 'dining'], { countable: true, aliases: ['butter knives', 'silverware', 'cutlery'] }),
  C('Spoons (table)', 'kitchen', ['kitchen', 'dining'], { countable: true, aliases: ['soup spoons', 'silverware', 'cutlery'] }),
  C('Teaspoons', 'kitchen', ['kitchen', 'dining'], { countable: true, aliases: ['small spoons'] }),
  C('Serving bowls', 'kitchen', ['kitchen', 'dining'], { countable: true }),
  C('Serving platters', 'kitchen', ['kitchen', 'dining'], { countable: true }),
  C('Salt & pepper shakers', 'kitchen', ['kitchen', 'dining']),
  C('Butter dish', 'kitchen', ['kitchen']),
  C('Sugar bowl / creamer', 'kitchen', ['kitchen']),
  C('Napkin holder', 'kitchen', ['kitchen', 'dining']),
  C('Cloth napkins', 'linen', ['dining', 'kitchen'], { countable: true }),
  C('Placemats', 'kitchen', ['dining', 'kitchen'], { countable: true }),
  C('Tablecloth', 'linen', ['dining']),
  C('Table runner', 'decor', ['dining']),

  // ── KITCHEN — STORAGE, CLEANING, SUPPLIES ──────────────────────────────────────────────────────
  C('Food storage containers', 'kitchen', ['kitchen'], { countable: true, aliases: ['tupperware'] }),
  C('Paper towel holder', 'other', ['kitchen']),
  C('Dish rack', 'kitchen', ['kitchen'], { aliases: ['drying rack'] }),
  C('Dish soap dispenser', 'other', ['kitchen']),
  C('Sponge holder', 'other', ['kitchen']),
  C('Kitchen towels', 'linen', ['kitchen'], { countable: true, aliases: ['dish towels'] }),
  C('Trash can', 'other', ['kitchen', 'bathroom', 'bedroom', 'office', 'living'], { aliases: ['bin', 'garbage can'] }),
  C('Recycling bin', 'other', ['kitchen']),
  C('Cleaning supplies caddy', 'other', ['kitchen', 'laundry'], { aliases: ['cleaning supplies'] }),
  C('Spice rack (basics)', 'kitchen', ['kitchen'], { aliases: ['spices'] }),
  C('Oil & vinegar set', 'kitchen', ['kitchen']),
  C('Fruit bowl', 'kitchen', ['kitchen', 'dining']),
  C('Bread box', 'kitchen', ['kitchen']),
  C('Utensil crock', 'kitchen', ['kitchen'], { aliases: ['utensil holder'] }),
  C('Step stool', 'other', ['kitchen', 'laundry']),
  C('Bar stools', 'furniture', ['kitchen', 'dining'], { countable: true, aliases: ['counter stools', 'stools'] }),
  C('Kitchen island / cart', 'furniture', ['kitchen']),

  // ── DINING ─────────────────────────────────────────────────────────────────────────────────────
  C('Dining table', 'furniture', ['dining', 'kitchen'], { aliases: ['table'] }),
  C('Dining chairs', 'furniture', ['dining', 'kitchen'], { countable: true, aliases: ['chairs'] }),
  C('Dining bench', 'furniture', ['dining']),
  C('High chair', 'furniture', ['dining', 'kitchen'], { aliases: ['baby chair'] }),
  C('Booster seat', 'furniture', ['dining']),
  C('Pendant / dining light', 'decor', ['dining', 'kitchen'], { aliases: ['chandelier'] }),
  C('Sideboard / buffet', 'furniture', ['dining']),
  C('Centerpiece', 'decor', ['dining']),

  // ── BEDROOM ────────────────────────────────────────────────────────────────────────────────────
  C('Bed frame', 'furniture', ['bedroom', 'living'], { brand: 'size', aliases: ['bed'] }),
  C('Headboard', 'furniture', ['bedroom'], { brand: 'size' }),
  C('Mattress', 'furniture', ['bedroom', 'living'], { brand: 'size' }),
  C('Mattress protector', 'linen', ['bedroom', 'living'], { brand: 'size' }),
  C('Mattress topper', 'linen', ['bedroom'], { brand: 'size' }),
  C('Box spring / foundation', 'furniture', ['bedroom'], { brand: 'size' }),
  C('Bunk bed', 'furniture', ['bedroom']),
  C('Trundle bed', 'furniture', ['bedroom']),
  C('Daybed', 'furniture', ['bedroom', 'office']),
  C('Crib', 'furniture', ['bedroom'], { aliases: ['pack n play', 'travel crib'] }),
  C('Crib mattress & sheets', 'linen', ['bedroom']),
  C('Pillows', 'linen', ['bedroom', 'living'], { countable: true, brand: 'size', aliases: ['bed pillows'] }),
  C('Pillowcases', 'linen', ['bedroom', 'laundry'], { countable: true, brand: 'size' }),
  C('Sheet sets', 'linen', ['bedroom', 'laundry'], { countable: true, brand: 'size', aliases: ['sheets', 'fitted sheet', 'flat sheet'] }),
  C('Duvet / comforter', 'linen', ['bedroom'], { countable: true, brand: 'size', aliases: ['comforter', 'duvet insert'] }),
  C('Duvet covers', 'linen', ['bedroom', 'laundry'], { countable: true, brand: 'size' }),
  C('Quilt / bedspread', 'linen', ['bedroom'], { brand: 'size' }),
  C('Extra blanket', 'linen', ['bedroom'], { countable: true, aliases: ['blanket'] }),
  C('Bed skirt', 'linen', ['bedroom']),
  C('Decorative pillows (bed)', 'decor', ['bedroom'], { countable: true, aliases: ['shams', 'euro pillows'] }),
  C('Nightstands', 'furniture', ['bedroom'], { countable: true, aliases: ['bedside table', 'night table'] }),
  C('Bedside lamps', 'decor', ['bedroom'], { countable: true, aliases: ['lamps'] }),
  C('Dresser', 'furniture', ['bedroom'], { aliases: ['chest of drawers'] }),
  C('Wardrobe / armoire', 'furniture', ['bedroom'], { aliases: ['closet', 'armoire'] }),
  C('Hangers', 'other', ['bedroom', 'entry', 'laundry'], { countable: true }),
  C('Closet organizer / shelves', 'furniture', ['bedroom']),
  C('Full-length mirror', 'decor', ['bedroom', 'entry']),
  C('Vanity / desk', 'furniture', ['bedroom']),
  C('Alarm clock / charger', 'electronics', ['bedroom'], { aliases: ['clock', 'alarm'] }),
  C('White noise machine', 'electronics', ['bedroom']),
  C('Laundry hamper', 'other', ['bedroom', 'bathroom', 'laundry'], { aliases: ['hamper'] }),
  C('Iron & ironing board', 'other', ['bedroom', 'laundry'], { aliases: ['iron'] }),
  C('Steamer', 'appliance', ['bedroom', 'laundry']),
  C('Reading chair', 'furniture', ['bedroom']),
  C('Blackout shades', 'decor', ['bedroom']),

  // ── BATHROOM ───────────────────────────────────────────────────────────────────────────────────
  C('Bath towels', 'linen', ['bathroom', 'laundry'], { countable: true, aliases: ['towels'] }),
  C('Hand towels', 'linen', ['bathroom', 'laundry'], { countable: true }),
  C('Washcloths', 'linen', ['bathroom', 'laundry'], { countable: true, aliases: ['face cloths'] }),
  C('Makeup towels (dark)', 'linen', ['bathroom'], { countable: true }),
  C('Pool / beach towels', 'linen', ['bathroom', 'laundry', 'balcony'], { countable: true, aliases: ['beach towels'] }),
  C('Bath robes', 'linen', ['bathroom', 'bedroom'], { countable: true }),
  C('Bath mat', 'linen', ['bathroom'], { aliases: ['bath rug'] }),
  C('Shower mat (non-slip)', 'other', ['bathroom']),
  C('Shower curtain / glass door', 'other', ['bathroom'], { aliases: ['enclosure'] }),
  C('Shower curtain', 'other', ['bathroom']),
  C('Shower liner', 'other', ['bathroom']),
  C('Shower curtain rod / rings', 'other', ['bathroom']),
  C('Glass shower door', 'other', ['bathroom']),
  C('Shower head', 'other', ['bathroom'], { aliases: ['showerhead', 'handheld'] }),
  C('Shower caddy / shelf', 'other', ['bathroom'], { aliases: ['caddy'] }),
  C('Soap dispenser', 'other', ['bathroom', 'kitchen'], { aliases: ['soap pump'] }),
  C('Shampoo / conditioner dispensers', 'other', ['bathroom'], { aliases: ['amenity dispensers'] }),
  C('Soap dish', 'other', ['bathroom']),
  C('Toothbrush holder', 'other', ['bathroom']),
  C('Tissue box cover', 'decor', ['bathroom', 'bedroom']),
  C('Toilet paper holder', 'other', ['bathroom']),
  C('Spare toilet paper holder', 'other', ['bathroom']),
  C('Toilet brush', 'other', ['bathroom']),
  C('Plunger', 'other', ['bathroom']),
  C('Towel bar / hooks', 'other', ['bathroom'], { aliases: ['towel rack', 'hooks'] }),
  C('Towel ring', 'other', ['bathroom']),
  C('Bathroom shelving / storage', 'furniture', ['bathroom'], { aliases: ['shelves', 'cabinet'] }),
  C('Hair dryer', 'appliance', ['bathroom', 'bedroom'], { aliases: ['blow dryer'] }),
  C('Magnifying mirror', 'decor', ['bathroom']),
  C('Scale', 'other', ['bathroom']),
  C('Bathroom trash can', 'other', ['bathroom']),
  C('Toilet seat', 'other', ['bathroom']),
  C('Bidet attachment', 'other', ['bathroom']),
  C('Grab bar', 'safety', ['bathroom']),
  C('Night light', 'electronics', ['bathroom', 'entry', 'bedroom']),

  // ── LAUNDRY & CLEANING ─────────────────────────────────────────────────────────────────────────
  C('Washer', 'appliance', ['laundry'], { brand: 'model', aliases: ['washing machine'] }),
  C('Dryer', 'appliance', ['laundry'], { brand: 'model' }),
  C('Washer / dryer combo', 'appliance', ['laundry'], { brand: 'model' }),
  C('Laundry basket', 'other', ['laundry', 'bedroom']),
  C('Drying rack', 'other', ['laundry', 'balcony']),
  C('Detergent', 'other', ['laundry']),
  C('Vacuum', 'appliance', ['laundry', 'entry'], { brand: 'model', aliases: ['dyson', 'hoover'] }),
  C('Robot vacuum', 'appliance', ['laundry', 'living'], { brand: 'model', aliases: ['roomba'] }),
  C('Broom & dustpan', 'other', ['laundry', 'kitchen'], { aliases: ['broom'] }),
  C('Mop & bucket', 'other', ['laundry', 'kitchen'], { aliases: ['mop', 'swiffer'] }),
  C('Spare light bulbs', 'other', ['laundry', 'entry'], { countable: true }),
  C('Spare batteries', 'other', ['laundry', 'entry'], { countable: true }),
  C('Lint roller', 'other', ['laundry', 'bedroom']),
  C('Sewing kit', 'other', ['laundry', 'bedroom']),
  C('Tool kit', 'other', ['laundry', 'entry']),
  C('Extension cord', 'electronics', ['laundry', 'living']),
  C('Utility shelving', 'furniture', ['laundry', 'other']),

  // ── OUTDOOR ────────────────────────────────────────────────────────────────────────────────────
  C('Outdoor chairs', 'furniture', ['balcony'], { countable: true, aliases: ['patio chairs'] }),
  C('Outdoor table', 'furniture', ['balcony'], { aliases: ['patio table', 'bistro table'] }),
  C('Outdoor sofa / sectional', 'furniture', ['balcony']),
  C('Lounge chairs', 'furniture', ['balcony'], { countable: true, aliases: ['chaise', 'sun lounger'] }),
  C('Outdoor cushions', 'decor', ['balcony'], { countable: true }),
  C('Outdoor rug', 'decor', ['balcony']),
  C('Umbrella (patio)', 'furniture', ['balcony'], { aliases: ['patio umbrella'] }),
  C('Grill', 'appliance', ['balcony'], { brand: 'model', aliases: ['bbq', 'barbecue'] }),
  C('Grill tools', 'other', ['balcony'], { aliases: ['bbq tools'] }),
  C('Grill cover', 'other', ['balcony']),
  C('Propane tank', 'other', ['balcony']),
  C('Fire pit', 'appliance', ['balcony']),
  C('Outdoor heater', 'appliance', ['balcony']),
  C('Outdoor light / string lights', 'decor', ['balcony'], { aliases: ['string lights'] }),
  C('Planters', 'decor', ['balcony'], { countable: true }),
  C('Hose', 'other', ['balcony']),
  C('Pool floats', 'other', ['balcony'], { countable: true }),
  C('Beach chairs', 'furniture', ['balcony', 'entry', 'laundry'], { countable: true }),
  C('Beach umbrella', 'other', ['balcony', 'entry', 'laundry']),
  C('Cooler', 'other', ['balcony', 'kitchen', 'laundry']),
  C('Bikes', 'other', ['balcony', 'other'], { countable: true }),
  C('Outdoor shower', 'other', ['balcony']),
  C('Hot tub', 'appliance', ['balcony'], { brand: 'model' }),

  // ── OFFICE ─────────────────────────────────────────────────────────────────────────────────────
  C('Desk', 'furniture', ['office', 'bedroom', 'living']),
  C('Desk chair', 'furniture', ['office', 'bedroom'], { aliases: ['office chair'] }),
  C('Desk lamp', 'decor', ['office', 'bedroom']),
  C('Monitor', 'electronics', ['office'], { brand: 'size' }),
  C('Printer', 'electronics', ['office']),
  C('Whiteboard', 'other', ['office']),
  C('Filing cabinet', 'furniture', ['office']),

  // ── KIDS & BABY ────────────────────────────────────────────────────────────────────────────────
  C('Pack n play / travel crib', 'furniture', ['bedroom', 'living', 'other'], { aliases: ['travel crib', 'pack and play'] }),
  C('Baby monitor', 'electronics', ['bedroom']),
  C('Baby bath', 'other', ['bathroom']),
  C('Outlet covers', 'safety', ['living', 'bedroom', 'kitchen'], { countable: true }),
  C('Toys', 'other', ['living', 'bedroom'], { countable: true }),
  C('Stair gate', 'safety', ['entry', 'living']),

  // ── SUPPLIES (consumables the walker still counts on day one) ─────────────────────────────────
  C('Toilet paper (stock)', 'other', ['bathroom', 'laundry'], { countable: true }),
  C('Paper towels (stock)', 'other', ['kitchen', 'laundry'], { countable: true }),
  C('Trash bags', 'other', ['kitchen', 'laundry']),
  C('Dishwasher pods', 'other', ['kitchen']),
  C('Hand soap (stock)', 'other', ['bathroom', 'kitchen']),
  C('Coffee / tea starter', 'other', ['kitchen']),
  C('Salt / pepper / oil starter', 'other', ['kitchen']),
]

const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9 ]+/g, ' ').replace(/\s+/g, ' ').trim()

/** Search the catalog for a query, the current room's items first. Empty query → what is typical for this room. */
export function searchCatalog(q: string, kind: RoomKind, limit = 12): CatalogItem[] {
  const nq = norm(q)
  const scored = CATALOG.map(it => {
    const name = norm(it.name); const al = (it.aliases || []).map(norm)
    let s = 0
    if (nq) {
      if (name === nq) s = 100
      else if (name.startsWith(nq)) s = 80
      else if (name.includes(nq)) s = 60
      else if (al.some(a => a === nq || a.startsWith(nq))) s = 55
      else if (al.some(a => a.includes(nq))) s = 45
      else if (nq.split(' ').every(w => name.includes(w) || al.some(a => a.includes(w)))) s = 35
      else return null
    } else s = 10
    if (it.kinds.includes(kind)) s += 20
    if (it.kinds[0] === kind) s += 5
    return { it, s }
  }).filter(Boolean) as { it: CatalogItem; s: number }[]
  scored.sort((a, b) => b.s - a.s || a.it.name.localeCompare(b.it.name))
  return scored.slice(0, limit).map(x => x.it)
}

/** The items most typical for a room kind — the chip strip under the search box. */
export function typicalFor(kind: RoomKind, limit = 14): CatalogItem[] {
  return CATALOG.filter(it => it.kinds[0] === kind).slice(0, limit)
}
