-- Owner Reports: generated owner-facing reports (guidebook-style share pages + PPTX export)
-- and stored monthly budgets (currently only 17 West has one; Performance vs Plan
-- auto-hides for scopes with no budget rows).

create table if not exists owner_reports (
  id          uuid primary key default gen_random_uuid(),
  code        text unique not null,                    -- unguessable share code (like guidebooks/audits)
  title       text not null default 'Owner Review',
  scope_label text,                                    -- e.g. "17 West"
  listing_ids jsonb not null default '[]'::jsonb,      -- guesty listing ids in scope
  period_start date not null,
  period_end   date not null,
  as_of        date not null,
  theme       text not null default 'capri',           -- capri | minimal | darklux
  status      text not null default 'draft',
  content     jsonb not null default '{}'::jsonb,      -- all sections; page renders + pptx exports this
  created_by  text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists owner_reports_code_idx on owner_reports (code);
create index if not exists owner_reports_updated_idx on owner_reports (updated_at desc);

create table if not exists owner_budgets (
  id           bigint generated by default as identity primary key,
  building_key text not null,                          -- rollup building name, e.g. "17 West"
  year         int  not null,
  month        int  not null,                          -- 1-12
  occupancy_pct numeric,                               -- 0-100
  adr           numeric,
  revpar        numeric,
  gross_revenue numeric,
  updated_at    timestamptz not null default now(),
  unique (building_key, year, month)
);

alter table owner_reports enable row level security;
alter table owner_budgets enable row level security;
-- Service-role writes only (same posture as other StayBoard tables).
