-- 021 — SUPERSEDED. DO NOT RUN. Nothing in the app needs it.
--
-- This was going to add `next_check_in`, `due_reason` and `nudged_on` to `claims` for the turnover
-- clock and the daily nudge. It never ran: on 2026-08-04 the Supabase dashboard stopped rendering
-- inside the automated browser (blank body, no editor, no console output) while status.supabase.com
-- reported every system operational — so migrations could not be applied at all that session.
--
-- Rather than leave a shipped feature waiting on a door nobody could open, the feature was rewritten
-- to need no schema change, and the rewrite turned out to be the better design:
--
--   next_check_in  COMPUTED ON READ (lib/claim-turnover.ts). Bookings move — a guest cancels, an
--                  owner blocks the unit, a same-day booking appears the morning after checkout. A
--                  column written once at claim-creation would be quietly wrong by then, and wrong
--                  in the direction that costs money. One indexed query per board load, never stale.
--   due_reason     DERIVED (lib/claims.ts → effectiveDue). `claims.due_on` holds the channel target;
--                  the turnover is applied on top at read time; a manual due date still wins.
--   nudged_on      app_settings key `claims_nudged_on`, a claim id -> date map pruned to open claims.
--
-- Kept as a file only so the numbering stays honest and nobody wonders what 021 was.
-- If you run it anyway it is harmless — the columns will simply sit unused.

select 'migration 021 is superseded; nothing to do' as note;
